debugging curl on container for testing it

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -6,25 +6,25 @@ on:
       - main
 
 jobs:
-  build-and-deploy:
+  build-and-upload-image:
     runs-on: self-hosted
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Set up Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.x
-
-      - name: Install dependencies
-        run: |
-          pip install --upgrade pip
-          pip install -r requirements.txt
-
-      - name: Run unit tests
-        run: python -m pytest python/tests.py
+#      - name: Set up Python
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: 3.x
+#
+#      - name: Install dependencies
+#        run: |
+#          pip install --upgrade pip
+#          pip install -r requirements.txt
+#
+#      - name: Run unit tests
+#        run: python -m pytest python/tests.py
 
       - name: Build Docker image
         run: docker build -t fibi .
@@ -34,15 +34,16 @@ jobs:
         run: docker run -d -p 8000:8000 fibi
 
       - name: Curl the container and check status
+        # RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:8000/?n=10)
         run: |
-          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:8000/?n=10)
-          if [[ "$RESPONSE" -eq 200 ]]; then
-            echo "HTTP request succeeded with status code 200"
-            exit 0  # Success exit code
-          else
-            echo "HTTP request failed with status code $RESPONSE"
-            exit 1  # Failure exit code
-          fi
+          curl -v http://localhost:8000/?n=10
+#          if [[ "$RESPONSE" -eq 200 ]]; then
+#            echo "HTTP request succeeded with status code 200"
+#            exit 0  # Success exit code
+#          else
+#            echo "HTTP request failed with status code $RESPONSE"
+#            exit 1  # Failure exit code
+#          fi
 
 #      - name: Login to DockerHub
 #        uses: docker/login-action@v1
