debugging curl on container for testing it

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -30,23 +30,19 @@ jobs:
         run: docker build -t fibi .
         working-directory: python
 
-      - name: Run the built container to test image
-        run: docker run -d -p 8000:8000 fibi
-
-      - name: let the webserver start
-        run: sleep 10
+      - name: Run the built container to test image, sleep a bit for the webserver to start
+        run: docker run -d -p 8000:8000 fibi; sleep 5
 
       - name: Curl the container and check status
-        # RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:8000/?n=10)
         run: |
-          curl -v http://0.0.0.0:8000/?n=10
-#          if [[ "$RESPONSE" -eq 200 ]]; then
-#            echo "HTTP request succeeded with status code 200"
-#            exit 0  # Success exit code
-#          else
-#            echo "HTTP request failed with status code $RESPONSE"
-#            exit 1  # Failure exit code
-#          fi
+          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:8000/?n=10)
+          if [[ "$RESPONSE" -eq 200 ]]; then
+            echo "HTTP request succeeded with status code 200"
+            exit 0  # Success exit code
+          else
+            echo "HTTP request failed with status code $RESPONSE"
+            exit 1  # Failure exit code
+          fi
 
 #      - name: Login to DockerHub
 #        uses: docker/login-action@v1
